queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: Automatic merge on approval to the main branch
    conditions:
      - "#approved-reviews-by>=1"
      - base=main
      - label=A:automerge
    actions:
      queue:
        name: default
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}

  - name: Automatic merge on approval to the main branch
    conditions:
      - "#approved-reviews-by>=0"
      - label=A:automerge
      - author=mergify
    actions:
      queue:
        name: default
      merge:
        method: squash
        commit_message_template: |
          {{ title }} (#{{ number }})
          {{ body }}

  - name: Backport patches to the release/v9.0.x branch
    conditions:
      - base=main
      - label=A:backport/v9.0.x
    actions:
      backport:
        branches:
          - release/v9.0.x
        assignees:
          - "{{ author }}"
        labels:
          - A:automerge
